#!/bin/sh

### BEGIN INIT INFO
# Provides:          tiberium_soul
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the tiberium soul server
# Description:       Starts the tiberium soul server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/tiberium_soul.sh
NAME=tiberium_soul
DESC="cloud platform agent"

test -x $DAEMON || DAEMON=/usr/bin/tiberium_soul.sh
test -x $DAEMON || DAEMON=/usr/local/bin/tiberium_soul.sh
test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" tiberium_soul
        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
            --exec $DAEMON -- --daemon || true
        log_end_msg 0
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" tiberium_soul
        start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/$NAME.pid \
            || true
        log_end_msg 0
        ;;

    restart|force-reload)
        log_daemon_msg "Restarting $DESC" tiberium_soul
        start-stop-daemon --stop --quiet --retry 30 --pidfile \
            /var/run/$NAME.pid || true
        start-stop-daemon --start --quiet --pidfile \
            /var/run/$NAME.pid --exec $DAEMON -- --daemon || true
        log_end_msg 0
        ;;

    status)
        status_of_proc -p /var/run/$NAME.pid "$DAEMON" tiberium_soul && exit 0 || exit $?
        ;;

    *)
        echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
